### ISSUE TITLE
Extracting a BufferedImage?

### ISSUE THREAD

**Issue by kxygk** [pallix/tikkba#12]
I'm trying to use tikkba with JavaFX and hitting some issues. If I could somehow get the internal BufferedImage, then I could convert it to a JavaFX Image and be done - but it doesn't seem to be possible or maybe I'm not seeing it. (I don't quite understand the internals..) I've gotten it working so far with  JSVGCanvas and Swing, but there is no way to really convert a JSVGCanvas to something JavaFX friendly.. so I'm a bit stuck (and unfortunately there aren't really many options for SVG + Clojure)

Does anyone have any ideas or suggestions?

**Comment by pallix** [comment]
Sorry I just saw your message!

I don't know how to do it but Tikkba is based on Apache Batik so you should have a look at the Batik API and see if you can export the DOM to a BufferedImage. They have a mailing list also, you could ask there.

Good luck!

**Comment by kxygk** [comment]
Hey thanks for getting back to me :)

I ended up solving this problem by using another Java library called "FranzXaver". (No idea what's going on under the hood there)
With a simple one-liner I turn the SVG XML string into a JavaFX Group object that I can drop it intomy GUI. see here: https://geokon-gh.github.io/asparapiss/#asparapiss.svg2jfx

Thanks for making the library! It's been very helpful and streamlined everthing for me

**Comment by pallix** [comment]
I am really happy that you find it useful :-)!
